import React, { useContext } from "react";
import "../module/core/asset/css/insight.scss";
import NothingToShow from "../module/core/component/NothingToShow";
import { Chart, registerables } from "chart.js";
import DataContext from "../module/core/context/DataContext";
import { saveAs } from "file-saver";
import { exportInsights } from "../utils/excel_utils";
import InsightsGraph from "../module/core/component/Graphs/InsightsGraph";
import InsightsTable from "../module/core/component/InsightsTable";
import { FaRegFileExcel } from "react-icons/fa6";
import RuntimeGraphSelector from "../module/core/component/RuntimeGraphSelector";

export default function InsightPage() {
  // const { appData } = useContext(DataContext);
  // console.log(appData);

  const appData = {
    "problem": {
        "nameOfProblem": "allocation",
        "numberOfSets": 2,
        "numberOfIndividuals": 30,
        "fitnessFunction": "DEFAULT",
        "evaluateFunctions": [
            "ceil(R2) + (15 / 2) * W3",
            "DEFAULT"
        ],
        "setNames": [
            "Set_1",
            "Set_2"
        ],
        "individualNames": [
            "Individual_1",
            "Individual_2",
            "Individual_3",
            "Individual_4",
            "Individual_5",
            "Individual_6",
            "Individual_7",
            "Individual_8",
            "Individual_9",
            "Individual_10",
            "Individual_1",
            "Individual_2",
            "Individual_3",
            "Individual_4",
            "Individual_5",
            "Individual_6",
            "Individual_7",
            "Individual_8",
            "Individual_9",
            "Individual_10",
            "Individual_11",
            "Individual_12",
            "Individual_13",
            "Individual_14",
            "Individual_15",
            "Individual_16",
            "Individual_17",
            "Individual_18",
            "Individual_19",
            "Individual_20"
        ],
        "characteristics": [
            "Characteristic_2",
            "Characteristic_3",
            "Characteristic_4",
            "Characteristic_5",
            "Characteristic_6",
            "Characteristic_7",
            "Characteristic_8",
            "Characteristic_9",
            "Characteristic_10",
            "Characteristic 10"
        ],
        "individualSetIndices": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
        ],
        "individualCapacities": [
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1,
            1
        ],
        "individualProperties": [
            [
                27,
                32,
                17,
                43,
                12,
                49,
                28,
                39,
                10,
                43
            ],
            [
                27,
                30,
                43,
                17,
                22,
                35,
                41,
                26,
                47,
                7
            ],
            [
                39,
                21,
                50,
                15,
                48,
                4,
                24,
                4,
                11,
                46
            ],
            [
                8,
                50,
                28,
                8,
                20,
                1,
                18,
                6,
                22,
                39
            ],
            [
                25,
                48,
                44,
                32,
                30,
                8,
                29,
                41,
                32,
                19
            ],
            [
                9,
                28,
                6,
                31,
                6,
                29,
                49,
                43,
                39,
                29
            ],
            [
                33,
                4,
                12,
                12,
                31,
                3,
                12,
                13,
                36,
                37
            ],
            [
                9,
                18,
                44,
                27,
                25,
                28,
                11,
                17,
                13,
                34
            ],
            [
                29,
                11,
                35,
                36,
                9,
                46,
                36,
                1,
                35,
                44
            ],
            [
                2,
                7,
                45,
                13,
                43,
                41,
                36,
                46,
                3,
                39
            ],
            [
                8,
                45,
                11,
                5,
                34,
                50,
                50,
                50,
                12,
                16
            ],
            [
                35,
                2,
                1,
                17,
                35,
                23,
                3,
                43,
                21,
                1
            ],
            [
                6,
                41,
                28,
                46,
                40,
                3,
                45,
                29,
                28,
                19
            ],
            [
                48,
                49,
                6,
                7,
                16,
                4,
                40,
                40,
                41,
                23
            ],
            [
                11,
                45,
                32,
                20,
                44,
                17,
                49,
                4,
                4,
                9
            ],
            [
                49,
                28,
                29,
                44,
                41,
                42,
                11,
                28,
                12,
                7
            ],
            [
                19,
                21,
                47,
                30,
                25,
                17,
                25,
                3,
                27,
                33
            ],
            [
                24,
                5,
                17,
                42,
                23,
                45,
                45,
                2,
                5,
                5
            ],
            [
                14,
                21,
                43,
                47,
                46,
                12,
                37,
                23,
                16,
                43
            ],
            [
                32,
                44,
                14,
                16,
                35,
                16,
                35,
                26,
                44,
                26
            ],
            [
                42,
                38,
                12,
                10,
                29,
                8,
                50,
                21,
                18,
                26
            ],
            [
                14,
                37,
                28,
                48,
                42,
                47,
                38,
                23,
                43,
                8
            ],
            [
                6,
                12,
                26,
                1,
                7,
                1,
                40,
                42,
                2,
                45
            ],
            [
                28,
                31,
                2,
                25,
                21,
                9,
                45,
                10,
                29,
                8
            ],
            [
                12,
                41,
                49,
                38,
                47,
                49,
                11,
                26,
                41,
                31
            ],
            [
                37,
                6,
                45,
                24,
                14,
                8,
                28,
                34,
                11,
                48
            ],
            [
                49,
                39,
                42,
                30,
                23,
                31,
                23,
                25,
                27,
                35
            ],
            [
                35,
                46,
                48,
                45,
                38,
                3,
                47,
                47,
                25,
                3
            ],
            [
                2,
                12,
                22,
                40,
                7,
                47,
                3,
                19,
                5,
                6
            ],
            [
                42,
                31,
                12,
                47,
                48,
                22,
                50,
                37,
                25,
                8
            ]
        ],
        "individualRequirements": [
            [
                22,
                25,
                19,
                28,
                33,
                33,
                14,
                6,
                39,
                43
            ],
            [
                4,
                45,
                8,
                16,
                30,
                45,
                1,
                25,
                49,
                47
            ],
            [
                22,
                48,
                1,
                29,
                14,
                30,
                7,
                9,
                5,
                10
            ],
            [
                29,
                19,
                37,
                30,
                21,
                31,
                0,
                28,
                19,
                13
            ],
            [
                0,
                32,
                11,
                1,
                2,
                32,
                2,
                42,
                36,
                9
            ],
            [
                12,
                7,
                13,
                38,
                8,
                15,
                46,
                40,
                18,
                6
            ],
            [
                26,
                15,
                21,
                20,
                38,
                48,
                8,
                47,
                19,
                17
            ],
            [
                48,
                20,
                17,
                25,
                22,
                44,
                42,
                16,
                47,
                27
            ],
            [
                12,
                12,
                4,
                17,
                19,
                9,
                24,
                42,
                40,
                26
            ],
            [
                29,
                26,
                46,
                33,
                49,
                6,
                18,
                9,
                22,
                8
            ],
            [
                31,
                41,
                1,
                36,
                24,
                33,
                32,
                33,
                36,
                3
            ],
            [
                2,
                14,
                43,
                1,
                4,
                34,
                3,
                46,
                26,
                35
            ],
            [
                19,
                37,
                1,
                17,
                27,
                37,
                48,
                49,
                28,
                6
            ],
            [
                12,
                13,
                37,
                6,
                5,
                3,
                15,
                6,
                7,
                2
            ],
            [
                30,
                31,
                5,
                50,
                27,
                48,
                25,
                41,
                4,
                2
            ],
            [
                47,
                17,
                11,
                12,
                16,
                7,
                37,
                46,
                36,
                3
            ],
            [
                35,
                39,
                26,
                46,
                1,
                29,
                24,
                9,
                42,
                41
            ],
            [
                49,
                3,
                14,
                32,
                48,
                47,
                4,
                12,
                22,
                35
            ],
            [
                48,
                6,
                0,
                12,
                16,
                13,
                2,
                10,
                40,
                4
            ],
            [
                20,
                20,
                14,
                7,
                10,
                34,
                7,
                21,
                5,
                46
            ],
            [
                4,
                29,
                49,
                47,
                32,
                46,
                18,
                25,
                5,
                37
            ],
            [
                39,
                13,
                33,
                16,
                30,
                11,
                28,
                4,
                17,
                12
            ],
            [
                26,
                21,
                49,
                10,
                17,
                37,
                32,
                15,
                35,
                24
            ],
            [
                8,
                45,
                25,
                43,
                32,
                26,
                22,
                32,
                48,
                10
            ],
            [
                47,
                1,
                16,
                8,
                35,
                27,
                17,
                49,
                33,
                13
            ],
            [
                45,
                31,
                47,
                21,
                11,
                23,
                4,
                18,
                11,
                49
            ],
            [
                42,
                20,
                46,
                7,
                17,
                21,
                10,
                16,
                33,
                38
            ],
            [
                10,
                31,
                35,
                21,
                19,
                50,
                1,
                16,
                39,
                18
            ],
            [
                3,
                35,
                13,
                20,
                22,
                38,
                42,
                41,
                21,
                34
            ],
            [
                20,
                36,
                29,
                9,
                34,
                36,
                9,
                29,
                12,
                17
            ]
        ],
        "individualWeights": [
            [
                0,
                6,
                0,
                3,
                5,
                6,
                9,
                8,
                1,
                7
            ],
            [
                5,
                7,
                7,
                7,
                3,
                4,
                4,
                0,
                9,
                1
            ],
            [
                9,
                4,
                2,
                6,
                2,
                1,
                3,
                6,
                9,
                0
            ],
            [
                5,
                1,
                1,
                2,
                9,
                5,
                6,
                6,
                0,
                8
            ],
            [
                2,
                9,
                0,
                5,
                7,
                2,
                9,
                1,
                6,
                9
            ],
            [
                7,
                9,
                4,
                7,
                8,
                7,
                8,
                0,
                6,
                1
            ],
            [
                6,
                10,
                6,
                5,
                7,
                8,
                4,
                6,
                6,
                9
            ],
            [
                8,
                6,
                4,
                4,
                7,
                2,
                2,
                2,
                1,
                8
            ],
            [
                6,
                5,
                0,
                0,
                2,
                5,
                4,
                2,
                3,
                6
            ],
            [
                8,
                8,
                8,
                6,
                1,
                7,
                2,
                7,
                5,
                7
            ],
            [
                6,
                4,
                6,
                2,
                7,
                6,
                0,
                3,
                8,
                1
            ],
            [
                2,
                7,
                8,
                9,
                5,
                1,
                5,
                8,
                6,
                7
            ],
            [
                3,
                4,
                10,
                1,
                3,
                9,
                6,
                4,
                1,
                9
            ],
            [
                8,
                8,
                9,
                8,
                2,
                5,
                8,
                3,
                2,
                3
            ],
            [
                8,
                2,
                10,
                9,
                8,
                5,
                7,
                7,
                5,
                0
            ],
            [
                8,
                3,
                6,
                7,
                7,
                8,
                6,
                4,
                3,
                6
            ],
            [
                4,
                7,
                6,
                10,
                3,
                8,
                6,
                8,
                1,
                1
            ],
            [
                1,
                7,
                4,
                9,
                10,
                9,
                9,
                8,
                3,
                7
            ],
            [
                7,
                9,
                2,
                2,
                9,
                0,
                2,
                8,
                0,
                9
            ],
            [
                9,
                7,
                6,
                3,
                3,
                6,
                8,
                2,
                10,
                2
            ],
            [
                3,
                8,
                1,
                1,
                9,
                0,
                6,
                6,
                6,
                9
            ],
            [
                4,
                2,
                4,
                5,
                0,
                1,
                1,
                1,
                1,
                9
            ],
            [
                7,
                5,
                9,
                6,
                6,
                1,
                10,
                7,
                8,
                10
            ],
            [
                6,
                6,
                8,
                5,
                7,
                7,
                2,
                2,
                1,
                6
            ],
            [
                9,
                6,
                4,
                10,
                5,
                2,
                1,
                2,
                4,
                0
            ],
            [
                6,
                9,
                5,
                5,
                5,
                6,
                6,
                5,
                9,
                2
            ],
            [
                3,
                6,
                10,
                7,
                2,
                6,
                10,
                9,
                6,
                0
            ],
            [
                5,
                2,
                10,
                6,
                4,
                7,
                4,
                8,
                4,
                4
            ],
            [
                4,
                1,
                3,
                1,
                4,
                6,
                0,
                4,
                5,
                3
            ],
            [
                7,
                4,
                6,
                8,
                9,
                6,
                8,
                4,
                3,
                2
            ]
        ],
        "excludePairs": {}
    },
    "result": {
        "data": {
            "matches": {
                "size": 30,
                "matches": [
                    [
                        14
                    ],
                    [
                        28
                    ],
                    [
                        17
                    ],
                    [
                        18
                    ],
                    [
                        21
                    ],
                    [
                        26
                    ],
                    [
                        24
                    ],
                    [
                        15
                    ],
                    [
                        20
                    ],
                    [
                        27
                    ],
                    [],
                    [],
                    [],
                    [],
                    [
                        0
                    ],
                    [
                        7
                    ],
                    [],
                    [
                        2
                    ],
                    [
                        3
                    ],
                    [],
                    [
                        8
                    ],
                    [
                        4
                    ],
                    [],
                    [],
                    [
                        6
                    ],
                    [],
                    [
                        5
                    ],
                    [
                        9
                    ],
                    [
                        1
                    ],
                    []
                ],
                "leftOvers": [
                    10,
                    11,
                    12,
                    13,
                    16,
                    19,
                    22,
                    23,
                    25,
                    29
                ],
                "allMatches": [
                    [
                        14
                    ],
                    [
                        28
                    ],
                    [
                        17
                    ],
                    [
                        18
                    ],
                    [
                        21
                    ],
                    [
                        26
                    ],
                    [
                        24
                    ],
                    [
                        15
                    ],
                    [
                        20
                    ],
                    [
                        27
                    ],
                    [],
                    [],
                    [],
                    [],
                    [
                        0
                    ],
                    [
                        7
                    ],
                    [],
                    [
                        2
                    ],
                    [
                        3
                    ],
                    [],
                    [
                        8
                    ],
                    [
                        4
                    ],
                    [],
                    [],
                    [
                        6
                    ],
                    [],
                    [
                        5
                    ],
                    [
                        9
                    ],
                    [
                        1
                    ],
                    []
                ]
            },
            "fitnessValue": 919.2676,
            "runtime": 3767,
            "computerSpecs": {
                "osFamily": "Windows",
                "osManufacturer": "Microsoft",
                "osVersion": "10",
                "cpuName": "AMD Ryzen 5 5500U with Radeon Graphics         ",
                "cpuPhysicalCores": 6,
                "cpuLogicalCores": 12,
                "totalMemory": "15.3 GiB"
            },
            "algorithm": "NSGAII",
            "setSatisfactions": [
                63.36666666666667,
                37.87777777777778,
                47.2935512763099,
                51.57658282921441,
                37.610416666666666,
                64.97307692307692,
                97.01702786377709,
                46.97565062388591,
                63.719298245614034,
                73.64270324045435,
                0,
                0,
                0,
                0,
                20.008682795698924,
                53.86397058823529,
                0,
                33.48571428571428,
                24.05,
                0,
                22.7027027027027,
                39.88601594483947,
                0,
                0,
                14.563636363636363,
                0,
                47.96412337662338,
                53.57644110275689,
                25.113553113553113,
                0
            ]
        },
        "params": {
            "runtime": 3767,
            "usedAlgorithm": "NSGAII",
            "distributedCoreParam": "all",
            "populationSizeParam": 1000,
            "generationParam": 100,
            "maxTimeParam": 5000
        }
    },
    "problemType": {
        "ordinal": 3,
        "displayName": "Many to Many",
        "endpoint": "/api/stable-matching-solver",
        "insightEndpoint": "/api/matching-problem-result-insights"
    },
    "insights": {
        "data": {
            "fitnessValues": {
                "eMOEA": [
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676
                ],
                "VEGA": [
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676
                ],
                "NSGAII": [
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676
                ],
                "NSGAIII": [
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676
                ],
                "IBEA": [
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676
                ],
                "PESA2": [
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676,
                    919.2676
                ]
            },
            "runtimes": {
                "eMOEA": [
                    3.664,
                    3.495,
                    3.473,
                    3.647,
                    3.476,
                    3.47,
                    3.466,
                    3.765,
                    3.686,
                    3.732
                ],
                "VEGA": [
                    0.394,
                    0.389,
                    0.383,
                    0.384,
                    0.395,
                    0.376,
                    0.372,
                    0.408,
                    0.528,
                    0.382
                ],
                "NSGAII": [
                    0.767,
                    0.699,
                    0.65,
                    0.768,
                    0.701,
                    0.7,
                    0.634,
                    0.684,
                    0.718,
                    0.7
                ],
                "NSGAIII": [
                    1.618,
                    1.619,
                    1.635,
                    1.601,
                    1.619,
                    1.66,
                    1.609,
                    1.652,
                    1.641,
                    1.797
                ],
                "IBEA": [
                    4.892,
                    4.938,
                    4.928,
                    4.879,
                    4.601,
                    4.732,
                    4.893,
                    4.826,
                    4.873,
                    4.871
                ],
                "PESA2": [
                    0.731,
                    0.714,
                    0.68,
                    0.703,
                    0.705,
                    0.66,
                    0.716,
                    0.713,
                    0.632,
                    0.695
                ]
            },
            "computerSpecs": {
                "osFamily": "Windows",
                "osManufacturer": "Microsoft",
                "osVersion": "10",
                "cpuName": "AMD Ryzen 5 5500U with Radeon Graphics         ",
                "cpuPhysicalCores": 6,
                "cpuLogicalCores": 12,
                "totalMemory": "15.3 GiB"
            }
        },
        "params": {
            "distributedCoreParam": "all",
            "populationSizeParam": 1000,
            "generationParam": 100,
            "maxTimeParam": 5000
        }
    }
}

  Chart.register(...registerables);

  const handleExportToExcel = async () => {
    const blob = await exportInsights(
      appData.insights.data.fitnessValues,
      appData.insights.data.runtimes,
      appData.insights.data.computerSpecs,
      appData.insights.params,
    );
    saveAs(blob, "insights.xlsx");
  };

  if (!appData || !appData.problem || !appData.insights) {
    return <NothingToShow />;
  }

  return (
    <div className="insight-page">
      <div className="text-center small px-5">
        {appData.problem.nameOfProblem}
      </div>
      <div className="fs-1 fw-bold">Insights</div>
      <div
        className="btn btn-success d-flex align-self-center justify-content-center border-1 p-3"
        onClick={handleExportToExcel}
      >
        <FaRegFileExcel className="me-0 fs-4" />
        Export Result
      </div>
      <div className="fitness-table">
        <InsightsTable fitnessValues={appData.insights.data.fitnessValues} />
        <p className="figure-description">
          Comparison of Fitness Values across different algorithms
        </p>
      </div>
      <div className="runtime-graph">
        <RuntimeGraphSelector runtimes={appData.insights.data.runtimes} />
      </div>
    </div>
  );
}
